config/routes.rb
Rails.application.routes.draw do
  root "links#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :links, except: %i[index new edit], param: :short_name
    end
  end

  resources :links, only: %i[index show destroy], param: :short_name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  before_validation :generate_short_name_and_password, on: :create

  validates :full_name,
            presence: true,
            length: { maximum: 250 },
            format: URI::regexp(%w[http https])

  validates :short_name,
            presence: true,
            uniqueness: true,
            length: { is: 5 }

  validates :password,
            presence: true,
            length: { is: 4 }

  def to_param
    short_name
  end

  default_scope -> { order(created_at: :desc) }

  private

    def generate_short_name_and_password
      new_short_name = SecureRandom.alphanumeric(5)
      if Link.find_by(short_name: new_short_name)
        generete_short_name
      else
        self.short_name = new_short_name
        self.password = SecureRandom.hex(2)
      end
    end
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  before_action :set_link, except: :create
  before_action :check_password, except: :create
  protect_from_forgery with: :null_session

  def show
    visit_this(@link)
    render :show, status: :ok
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      render :show, status: :created
    else
      render json: { msg: "Invalid format" }, status: :unprocessable_entity
    end
  end

  def update
    if @link.update(link_params)
      render :show, status: :ok
    else
      render json: { msg: "Invalid format" }, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    render json: { msg: "Link deleted" }, status: :ok
  end

  private

    def set_link
      if !(@link = Link.find_by(short_name: params[:short_name])).nil?
        @link
      else
        render json: { status: "ERROR", message: "Not found" },
                     status: :not_found
      end
    end

    def check_password
      unless @link.password.eql?(params[:password])
        render json: { msg: "Incorrect password" },
                     status: :forbidden and return
      end
    end

    def link_params
      params.permit(:full_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def visit_this(link)
    link.update(quantity_visit: @link.quantity_visit + 1)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin"
  before_action :set_link, only: %i[show destroy]

  def index
    links = Link.all.paginate(page: params[:page], per_page: 6)
    @links =
      if !params[:commit].equal?("Search")
        search_link = Link.where(short_name: params[:short_name])
        search_link.present? ? search_link : links
      else
        links
      end
  end

  def show
    visit_this(@link)
    redirect_to @link.full_name
  end

  def destroy
    @link.destroy
    redirect_to links_url
  end

  private

    def set_link
      if !(@link = Link.find_by(short_name: params[:short_name])).nil?
        @link
      else
        redirect_to :root
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def useless_link?(link)
    link.updated_at < 2.months.ago
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebSistemsTestTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_link.html.erb
<article class="card">
  <div class="card__header">
    <time class="card__time">
      <%= link.created_at.to_formatted_s(:long_ordinal) %>
    </time>
    <span class="card__views"><%= link.quantity_visit %> views</span>
    <%= link_to '×', link, method: :delete, class: "card__delete",
                           data: { confirm: 'Are you sure?' } %>
  </div>
  <div class="card__body">
    <div class="card__short-link <%= 'card__short-link_useless' if useless_link?(link) %>">
      <%= link_to link.short_name, link, target: "_blank" %>
    </div>
    <div class="card__full-link"><%= link.full_name %></div>
  </div>
  <div class="card__footer">
    Last visited <%= time_ago_in_words(link.updated_at) %> ago.
  </div>
</article>

app/views/links/index.html.erb
<div class="page">
  <section class="background">
    <div class="background__container">
      <h1 class="background__title background__title_shadow"><%= link_to  "short-links", :root %></h1>
      <div class="background__subtitle background__subtitle_shadow">My test-task for Web-systems</div>
    </div>
  </section>
  <main class="content _anim-items _anim-no-hide">
    <section class="search">
      <div class="search__container">
        <%= form_tag(links_path, method: 'get') do %>
        <%= text_field_tag :short_name, nil, placeholder: "Short link..",
                                        required: true, pattern: "[a-zA-Z0-9]{5}",
                                        maxlength: "5", class: "search__input" %>
        <%= submit_tag "Search", class: "search__btn" %>
        <% end %>
      </div>
    </section>
    <section class="cards">
      <div class="cards__container">
        <% if @links.any? %>
          <%= render @links %>
        <% else %>
          <div class="cards__empty">Unfortunately, now we haven't one link, but soon they'll appear<div>
        <% end %>
      </div>
    </section>
    <% if @links.count > 1 %>
    <section class="paginate">
      <div class="paginate__container">
        <%= will_paginate @links, page_links: false %>
      </div>
    </section>
    <% end %>
  </main>
</div>